---
title: "decathlon_data_WIP"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(readr)
library(tidyr)
library(tibble)
library(stringr)

decathlon <- read_rds("raw_data/decathlon.rds")

decathlon <- clean_names(decathlon)
```

```{r}
view(decathlon)
glimpse(decathlon)
row.names(decathlon)


```
```{r}
decathlon_name_col <- rownames_to_column(decathlon, var = "name")

decathlon_formatted <- decathlon_name_col %>% 
  mutate(name = str_to_lower(name))

decathlon_formatted %>% 
  rename(javelin = javeline)

clean_decathlon <- decathlon %>%
    rownames_to_column(var = "name") %>%
    mutate(name = str_to_lower(name)) %>%
    rename("100m_time_s" = x100m,
           "long_jump_distance_m" = long_jump,
           "shot_put_distance_m" = shot_put,
           "high_jump_distance_m" = high_jump,
           "400m_time_s" = x400m,
           "110m_hurdles_time_s" = x110m_hurdle,
           "discus_distance_m" = discus,
           "pole_vault_height_m" = pole_vault,
           "javelin_throw_distance_m" = javeline,
           "1500m_time_s" = x1500m,
           "ranking" = rank,
           "total_points" = points
           )
  
view(clean_decathlon)

unique(clean_decathlon)

summary(clean_decathlon)

clean_decathlon %>% 
  select(name) %>% 
  group_by(name) %>% 
  count()
  
```

