---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(tidyr)
library(readxl)
library(stringr)
```

```{r}
candy_2015 <- read_excel("raw_data/boing-boing-candy-2015.xlsx")
candy_2016 <- read_excel("raw_data/boing-boing-candy-2016.xlsx")
candy_2017 <- read_excel("raw_data/boing-boing-candy-2017.xlsx")
```

```{r}
# clean and format columns and column headings.
candy_2015 <- clean_names(candy_2015)

#view(candy_2015)
#colnames(candy_2015)
#head(candy_2015)
#dim(candy_2015)
#summary(candy_2015)

## removed columns which i did not believe would be required to answer the given
## analysis questions.

candy_2015_concise <- candy_2015 %>% 
  select(how_old_are_you:york_peppermint_patties)

candy_2015_rename <- candy_2015_concise %>% 
  rename(age = how_old_are_you,
         trick_or_treating = are_you_going_actually_going_trick_or_treating_yourself,
         bonkers_the_candy = bonkers,
         licorice_yes_black = licorice)

#list(colnames(candy_2015_rename))

# Removed any item columns (total 19) from data base that I did not consider to be "candy".
# Candy feautures sugar as a prinicipal ingredient.
# Removed any candy bars which were fictional
# Removed any miscellaneous items

candy_2015_rename_concise <- candy_2015_rename %>% 
  select(-box_o_raisins, -cash_or_other_forms_of_legal_tender, 
         -dental_paraphenalia, -generic_brand_acetaminophen, -glow_sticks, 
         -broken_glow_stick, -creepy_religious_comics_chick_tracts, -healthy_fruit, 
         -hugs_actual_physical_hugs, -kale_smoothie, -lapel_pins, -spotted_dick,
         -peterson_brand_sidewalk_chalk, -peanut_butter_jars, -white_bread, 
         -whole_wheat_anything, - minibags_of_chips, -pencils,
         - vials_of_pure_high_fructose_corn_syrup_for_main_lining_into_your_vein,
         - joy_joy_mit_iodine, -vicodin, - senior_mints, -mint_juleps, -sweetums)

```

```{r}
candy_2016 <- clean_names(candy_2016)
#head(candy_2016)
#view(candy_2016)
#dim(candy_2016)

candy_2016_concise <- candy_2016 %>% 
  select(are_you_going_actually_going_trick_or_treating_yourself:york_peppermint_patties)

candy_2016_rename <- candy_2016_concise %>% 
  rename(trick_or_treating = are_you_going_actually_going_trick_or_treating_yourself,
         sex = your_gender,
         age = how_old_are_you,
         country = which_country_do_you_live_in,
         state_province_county = which_state_province_county_do_you_live_in
         )

candy_2016_rename_concise <- candy_2016_rename %>% 
  select(-bonkers_the_board_game, -boxo_raisins, -broken_glow_stick, 
         -cash_or_other_forms_of_legal_tender, -chardonnay, 
         -creepy_religious_comics_chick_tracts, -dental_paraphenalia,
         -generic_brand_acetaminophen, -glow_sticks, -healthy_fruit,
         -hugs_actual_physical_hugs, -kale_smoothie, - minibags_of_chips, -pencils,
         -person_of_interest_season_3_dvd_box_set_not_including_disc_4_with_hilarious_outtakes,
         -spotted_dick, -vicodin, -white_bread, -whole_wheat_anything,
         - vials_of_pure_high_fructose_corn_syrup_for_main_lining_into_your_vein,
         -joy_joy_mit_iodine, -senior_mints, mint_juleps, -sweetums_a_friend_to_diabetes, 
         -senior_mints, -mint_juleps)


```


```{r}
candy_2017 <- clean_names(candy_2017)
#view(candy_2017)

candy_2017_concise <- candy_2017 %>% 
  select(q1_going_out:q6_york_peppermint_patties) 

candy_2017_rename_concise <- candy_2017_concise %>%
  rename(trick_or_treating = q1_going_out,
         sex = q2_gender,
         age = q3_age,
         country = q4_country,
         state_province_county = q5_state_province_county_etc,
         x100_grand_bar = q6_100_grand_bar,
         
         )

candy_2017_rename_concise <- candy_2017_rename_concise %>% 
  select(-q6_bonkers_the_board_game, -q6_boxo_raisins, -q6_broken_glow_stick, 
         -q6_cash_or_other_forms_of_legal_tender, -q6_chardonnay, 
         -q6_creepy_religious_comics_chick_tracts, -q6_dental_paraphenalia,
         -q6_generic_brand_acetaminophen, -q6_glow_sticks, -q6_healthy_fruit,
         -q6_hugs_actual_physical_hugs, -q6_senior_mints, -q6_kale_smoothie, 
         -q6_minibags_of_chips, -q6_mint_juleps, -q6_pencils,
         -q6_real_housewives_of_orange_county_season_9_blue_ray,
         -q6_sandwich_sized_bags_filled_with_boo_berry_crunch,
         -q6_spotted_dick, -q6_vicodin, -q6_white_bread, -q6_whole_wheat_anything,
         -q6_vials_of_pure_high_fructose_corn_syrup_for_main_lining_into_your_vein,
         -q6_joy_joy_mit_iodine, -q6_senior_mints, -q6_sweetums_a_friend_to_diabetes)

q6_pattern <- "q6\\_"

colnames(candy_2017_rename_concise) <- 
  str_replace_all(colnames(candy_2017_rename_concise), q6_pattern, "" )




```
 
```{r}
#performed full join to keep all data from the three datasets and format all 
#common columns together.

candy_2015_2016 <- full_join(candy_2015_rename_concise, candy_2016_rename_concise)

candy_2015_2016_2017 <- full_join(candy_2015_2016, candy_2017_rename_concise)

#colnames(candy_2015_2016_2017)

```

```{r}

#To deal with age column I decided to only work with values that contained numbers, 
#decimals or were NA. the limitation of this approach is that some ages written in
#chracters may have been omitted. However this is a fast way of removing comments
#written in the age column. 

age_pattern_extract <- "\\d+\\.?\\d*|NA"
# The above pattern was used to extract all numbers, numbers with decimals and NAs.
# \\d+ Matches one or more digits (0-9).
# \\.? Matches an optional decimal point (escaped with a backslash since it has 
# a  special meaning in regular expressions).
# \\d*: Matches zero or more digits after the decimal point.
# |: The pipe symbol separates two alternatives. In this case, it separates the 
# |pattern for numbers from the pattern for the string "NA".
# NA: Matches the string "NA".
# anything that contained characters/letters was converted to NA and then to 0. 

age_cleaned <- candy_2015_2016_2017 %>% 
  mutate(age = str_extract(age, age_pattern_extract),
         age = as.numeric(ifelse(is.na(age), 0, age)))
  

# age_cleaned %>% 
#   group_by(age) %>% 
#   summarise(count = n()) %>% 
#   arrange(desc(count))

#converted any values that were zero or greater than 100 years to NAs 
candy_info_age_cleaned <- age_cleaned %>% 
  mutate(age = if_else(age < 1 | age > 100, NA, age))

# candy_info_age_cleaned %>% 
#    group_by(age) %>% 
#    summarise(count = n()) %>% 
#    arrange(desc(count))

```

```{r}
#renamed and re-organised columns structure

candy_info_cleaned <- candy_info_age_cleaned %>% 
 rename(anon_brown_globs_orange_black_wrappers = 
          anonymous_brown_globs_that_come_in_black_and_orange_wrappers,
        restaurant_candy = candy_that_is_clearly_just_the_stuff_given_out_for_free_at_restaurants,
        black_licorice = licorice_yes_black,
        chick_o_sticks = chick_o_sticks_we_don_t_know_what_that_is
        ) %>% 
  select(-mint_leaves)

```

```{r}
names(candy_info_cleaned)

candy_info_cleaned %>% 
    group_by(country) %>% 
    summarise(count = n()) %>% 
    arrange(desc(count))
```

